[package]
name = "qrand_core"
version = "0.1.0"
authors = ["rusty-octopus <octopus@posteo.net>"]
edition = "2018"
license = "MIT"

[dependencies]
rd_alphas = {path="../rd_alphas", optional=true}

[features]
sobol = []
rd = ["rd_alphas"]
