[package]
name = "qrand_core"
version = "0.31.0"
authors = ["rusty-octopus <octopus@posteo.net>"]
edition = "2018"
license = "MIT"

[build-dependencies]
qrand_rd_alphas = {path="../qrand_rd_alphas", optional=true}

[features]
std_interface = []
rd = ["qrand_rd_alphas"]
sobol = []